steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/music-player/music-player:tag1 .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        docker run us-west2-docker.pkg.dev/$PROJECT_ID/music-player/music-player:tag1
        # Call your API here after running the Docker image
        #curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' https://your-api-endpoint.com/api
        curl --request GET --url http://flow-api.viasocket.com/users/me --header 'Authorization: {{token}}'

  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/music-player/music-player:tag1'
